name: Gitleaks Secret Scan

on:
  pull_request:
  pull_request_target:
  merge_group:
  push:
    branches: [ main, develop ]
  repository_dispatch:
    types: [security-scan, gitleaks-scan]
  workflow_dispatch:
    inputs:
      blocking:
        description: 'Block workflow on findings'
        required: false
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      actions: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Gitleaks
        run: |
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.0_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/
          gitleaks version
      
      - name: Run Gitleaks scan
        id: scan
        run: |
          BLOCKING="${{ github.event.inputs.blocking || 'true' }}"
          
          if [ "$BLOCKING" = "true" ]; then
            echo "Running in BLOCKING mode - will fail on findings"
            EXIT_CODE=1
          else
            echo "Running in NON-BLOCKING mode - will not fail on findings"
            EXIT_CODE=0
          fi
          
          gitleaks detect \
            --source=. \
            --report-format=sarif \
            --report-path=gitleaks-results.sarif \
            --exit-code=$EXIT_CODE \
            --verbose || [ "$BLOCKING" = "false" ]
      
      - name: Create empty SARIF if needed
        if: always()
        run: |
          if [ ! -f gitleaks-results.sarif ]; then
            cat > gitleaks-results.sarif << 'EOF'
          {
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "Gitleaks",
                    "version": "8.18.0"
                  }
                },
                "results": []
              }
            ]
          }
          EOF
          fi
      
      - name: Display results
        if: always()
        run: |
          BLOCKING="${{ github.event.inputs.blocking || 'true' }}"
          echo "Running in $([ "$BLOCKING" = "true" ] && echo "BLOCKING" || echo "NON-BLOCKING") mode"
          
          if [ -f gitleaks-results.sarif ]; then
            SECRETS=$(jq '[.runs[].results[]] | length' gitleaks-results.sarif 2>/dev/null || echo "0")
            echo "Gitleaks scan completed with $SECRETS potential secrets found"
            
            if [ "$SECRETS" -gt 0 ]; then
              echo "Potential secrets detected:"
              jq -r '.runs[].results[] | "- \(.ruleId): \(.message.text) (\(.locations[0].physicalLocation.artifactLocation.uri))"' gitleaks-results.sarif | head -10
            fi
          else
            echo "No SARIF file generated"
          fi
      
      - name: Upload to DefectDojo
        if: always()
        run: |
          if [ -f gitleaks-results.sarif ]; then
            if [ -n "${{ secrets.DEFECTDOJO_URL }}" ] && [ -n "${{ secrets.DEFECTDOJO_TOKEN }}" ]; then
              echo "Uploading results to DefectDojo..."
              curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
                -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
                -F "scan_type=Gitleaks Scan" \
                -F "file=@gitleaks-results.sarif" \
                -F "product_name=${{ github.repository }}" \
                -F "engagement_name=Security Scan - $(date +%Y-%m-%d)" \
                -F "test_title=Gitleaks Secret - ${{ github.sha }}" \
                -F "active=true" \
                -F "verified=false" \
                -F "scan_date=$(date +%Y-%m-%d)" \
                -F "tags=gitleaks,secrets,credentials" || echo "DefectDojo upload failed"
            else
              echo "DefectDojo secrets not configured - skipping upload"
            fi
          fi
      
      - name: Upload SARIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-sarif
          path: gitleaks-results.sarif
          retention-days: 30
      
      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            if (fs.existsSync('gitleaks-results.sarif')) {
              const sarif = JSON.parse(fs.readFileSync('gitleaks-results.sarif', 'utf8'));
              const results = sarif.runs?.[0]?.results || [];
              const blocking = '${{ github.event.inputs.blocking || 'true' }}' === 'true';
              
              const body = `## 🔍 Gitleaks Secret Scan Results
              
              **Mode**: ${blocking ? '🚫 Blocking' : '⚠️ Non-blocking'}
              **Secrets found**: ${results.length}
              
              ${results.length > 0 ? 
                `⚠️ Potential secrets detected. ${blocking ? 'Workflow will fail.' : 'Review recommended.'}` : 
                '✅ No secrets detected.'
              }`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            }