name: Semgrep Security Scan

on:
  pull_request:
  pull_request_target:
  merge_group:
  push:
    branches: [ main, develop ]
  repository_dispatch:
    types: [security-scan, semgrep-scan]
  workflow_dispatch:
    inputs:
      blocking:
        description: 'Block workflow on findings'
        required: false
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      actions: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Semgrep
        run: pip install semgrep
      
      - name: Run Semgrep scan
        id: scan
        run: |
          BLOCKING="${{ github.event.inputs.blocking || 'true' }}"
          
          if [ "$BLOCKING" = "true" ]; then
            echo "Running in BLOCKING mode - will fail on findings"
            semgrep \
              --config=auto \
              --sarif \
              --output=semgrep.sarif \
              --no-git-ignore \
              --error \
              --severity=ERROR \
              .
          else
            echo "Running in NON-BLOCKING mode - will not fail on findings"
            semgrep \
              --config=auto \
              --sarif \
              --output=semgrep.sarif \
              --no-git-ignore \
              . || true
          fi
      
      - name: Display results
        if: always()
        run: |
          if [ -f semgrep.sarif ]; then
            FINDINGS=$(jq '[.runs[].results[]] | length' semgrep.sarif 2>/dev/null || echo "0")
            echo "Semgrep scan completed with $FINDINGS findings"
            
            if [ "$FINDINGS" -gt 0 ]; then
              echo "Found vulnerabilities:"
              jq -r '.runs[].results[] | "- \(.ruleId): \(.message.text)"' semgrep.sarif | head -10
            fi
          else
            echo "No SARIF file generated"
          fi
      
      - name: Upload to DefectDojo
        if: always()
        run: |
          if [ -f semgrep.sarif ]; then
            if [ -n "${{ secrets.DEFECTDOJO_URL }}" ] && [ -n "${{ secrets.DEFECTDOJO_TOKEN }}" ]; then
              echo "Uploading results to DefectDojo..."
              curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
                -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
                -F "scan_type=Semgrep JSON Report" \
                -F "file=@semgrep.sarif" \
                -F "product_name=${{ github.repository }}" \
                -F "engagement_name=Security Scan - $(date +%Y-%m-%d)" \
                -F "test_title=Semgrep SAST - ${{ github.sha }}" \
                -F "active=true" \
                -F "verified=false" \
                -F "scan_date=$(date +%Y-%m-%d)" \
                -F "tags=semgrep,sast,automated" || echo "DefectDojo upload failed"
            else
              echo "DefectDojo secrets not configured - skipping upload"
            fi
          fi
      
      - name: Upload SARIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif
          retention-days: 30
      
      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            if (fs.existsSync('semgrep.sarif')) {
              const sarif = JSON.parse(fs.readFileSync('semgrep.sarif', 'utf8'));
              const results = sarif.runs?.[0]?.results || [];
              const blocking = '${{ github.event.inputs.blocking || 'true' }}' === 'true';
              
              const body = `## 🔍 Semgrep Security Scan Results
              
              **Mode**: ${blocking ? '🚫 Blocking' : '⚠️ Non-blocking'}
              **Findings**: ${results.length}
              
              ${results.length > 0 ? 
                `⚠️ Security issues detected. ${blocking ? 'Workflow will fail.' : 'Review recommended.'}` : 
                '✅ No security issues found.'
              }`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            }